# Creds will get pulled from the standard AWS creds locations seen here:
# http://docs.aws.amazon.com/sdkforruby/api/Aws/Credentials.html
# expires_in (Integer) — default: 900 — The number of seconds before the presigned URL expires. Defaults to 15 minutes.
# secure (Boolean) — default: true — When false, a HTTP URL is returned instead of the default HTTPS URL.
-
  bucket: your_bucket_name_here
  profile: your_profile_name_here_from_your_aws_creds_file
  secure: true
  expires_in: 3600  
